### PR TITLE
fix: invalid bufnr on exiting some windows

### PR DESCRIPTION
**Pull request by Gnarus-G**
If you agree with my conclusion about issue #4

### CODE REVIEW

**Comment by luckasRanarison** [comment]
You're correct the bufnr taken in the closure produce the error but if you take the bufnr from the argument of the callback it'll fire even if the buffer hasn't tailwind-language-server attached to it. The solution would be adding `pattern` to the autocmd function and set it to the bufnr.

**Comment by Gnarus-G** [comment]
Really. You mean this would work?
```lua
  vim.api.nvim_create_autocmd(color_events, {
    group = vim.g.tailwind_tools.color_au,
    buffer = bufnr,
    callback = function(a)
      if not state.color.enabled then return end
      if a.event == "TextChangedI" then
        debounced_color_request(bufnr)
      elseif vim.startswith(a.event, "Cursor") == state.conceal.enabled then
        M.color_request(bufnr)
      end
    end,
  })
```

**Comment by luckasRanarison** [comment]
It should because it limits the scope of the autocmd to the current buffer, previously it was not and the callback took the invalid bufnr.

**Comment by Gnarus-G** [comment]
I see. Maybe I'll play around with it to really understand. I'll make the change and update the PR.

**Comment by luckasRanarison** [comment]
Thanks for the PR!

**Pull request merged**
